<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Reviews without a delivered order behind them were generated by seeders; keep them for the
     * admin but take them off the storefront.
     */
    public function up(): void
    {
        DB::table('reviews')
            ->where('is_approved', true)
            ->where(function ($query) {
                $query->whereNull('order_id')
                    ->orWhereNotExists(function ($orders) {
                        $orders->selectRaw('1')
                            ->from('orders')
                            ->whereColumn('orders.id', 'reviews.order_id')
                            ->whereColumn('orders.user_id', 'reviews.user_id')
                            ->where('orders.order_status', 'completed');
                    });
            })
            ->update(['is_approved' => false]);
    }

    public function down(): void
    {
        // Hidden reviews can be restored individually from the admin; nothing to undo automatically.
    }
};
